// Auto-generated by deploy.sh - Last updated: Fri Nov 21 03:29:57 CST 2025
export const PACKAGE_ID = "0x4776f4755a521d82bce03277bc8b5e372f96b2b2df77fce3090ae6c797930eb7";
export const REGISTRY_ID = "0x4e5dfe1c6dec7dd0b3bfdf64573935f93d46f71ed9d3c0d55c4ef00899c52759";
export const MODULE_NAME = "model_hub";
