// Auto-generated by deploy.sh - Last updated: Thu Nov 20 22:37:42 CST 2025
export const PACKAGE_ID = "0x4fb1cd3aeaa949218679193fb6fb97dba9fc7c60ece41a65b645149299fb3ca9";
export const REGISTRY_ID = "0xc9271c813d1fd86d0ba161fc59dafcc0f8ff4a846d2a7792a56200933059312e";
export const MODULE_NAME = "model_hub";
